### ISSUE TITLE
Use Google Translate API for translations

### ISSUE THREAD

**Issue by JustinMi** [BerkeleyAutomation/malasakit-v1#39]
This enables easier scaling for translations--if we want to add more languages, or add more questions.

**Comment by jonathan-j-lee** [comment]
To clarify, this issue calls for pulling translations from Google Translate into the local database so that field staff can look them over without onerous setup. We'll still want to keep translations in the database (i.e. not translating live) for the following reasons: 
1. Having a human look over all translations would reduce the odds of mistakes (we're not translating in bulk, so this should be feasible).
2. Poor network connectivity would interfere with live translation.

**Comment by jonathan-j-lee** [comment]
No longer relevant.
